### ISSUE TITLE
NPM giving Error

### ISSUE THREAD

**Issue by milahnmartin** [itschip/create-fivem-app#12]
Hey Guys, i have been using this for a while, i recently reinstalled windows and now when i try to run the command in terminal node gives me this error:

npm ERR! code ENOVERSIONS
npm ERR! No versions available for create-fivem-app

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bluev\AppData\Local\npm-cache\_logs\2021-06-15T18_40_31_219Z-debug.log

not sure what this means or what to do, appreciate the work you guys do <3

**Comment by itschip** [comment]
Try agian now :)

**Comment by milahnmartin** [comment]
> Try agian now :)


C:\Users\bluev>npm i create-fivem-app --global
npm WARN tarball tarball data for create-fivem-app@https://registry.npmjs.org/create-fivem-app/-/create-fivem-app-2.3.0.tgz (sha512-xiVzyIK+gK3KCKPzmMFnlHEIi6rov0USO7bvPM1PTpjY4rK+BJVpiwCXKhf09q5FxTMN3AB3K5pypt5Quwe/pQ==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for create-fivem-app@https://registry.npmjs.org/create-fivem-app/-/create-fivem-app-2.3.0.tgz (sha512-xiVzyIK+gK3KCKPzmMFnlHEIi6rov0USO7bvPM1PTpjY4rK+BJVpiwCXKhf09q5FxTMN3AB3K5pypt5Quwe/pQ==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-xiVzyIK+gK3KCKPzmMFnlHEIi6rov0USO7bvPM1PTpjY4rK+BJVpiwCXKhf09q5FxTMN3AB3K5pypt5Quwe/pQ== integrity checksum failed when using sha512: wanted sha512-xiVzyIK+gK3KCKPzmMFnlHEIi6rov0USO7bvPM1PTpjY4rK+BJVpiwCXKhf09q5FxTMN3AB3K5pypt5Quwe/pQ== but got sha512-zmPg8/SP7uX45gOe8lVxC7fMK+CjEGc81wUidAZ7C6J0P40JkIB6ChQUywRa0MqFHuTFJuZp0VIvbA0eAqSN6w==. (13431 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bluev\AppData\Local\npm-cache\_logs\2021-06-15T18_47_41_464Z-debug.log

C:\Users\bluev>cfa-create
'cfa-create' is not recognized as an internal or external command,
operable program or batch file.



this is what im getting now

**Comment by itschip** [comment]
Uninstall 'create-fivem-app' globally, then install it globally again.
